default: &default
  adapter: postgresql
  pool: 16
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: version_bot
  host: localhost

test:
  <<: *default
  database: version_bot_test
  host: localhost

production:
  <<: *default
  database: version_bot
  host: localhost
